### ISSUE TITLE
Can't change name associated with account

### ISSUE THREAD

**Issue by RisingFisan** [Hackathonners/swap#19]
### Expected Behavior
When a student changes their name on the university records, the name associated with their swap account should also automatically change, or there should be a way to manually change it.

### Current Behavior
It seems like there's no way of changing a name associated with an account, either manually or automatically.

### Possible Solution
If syncing the swap account with the university records to check for any name changes is not possible or very difficult, it should at least be possible to manually change the name of an account on the website.

### Context
This issue doesn't affect most students, but it affects students who legally changed their name, students who got married and changed their last name, and especially transgender students who changed their name and gender on their records, and don't want to have to use their old name when using swap.
Personally, I legally changed my name last year, and I changed it on my records as well, but that didn't change the name on my swap account, and I can't find a way to manually change it.

**Comment by fntneves** [comment]
Hi @RisingFisan,

Thank you for opening this issue.

>If syncing the swap account with the university records to check for any name changes is not possible or very difficult...
SWAP is not an official project of the university. Therefore, it is not permitted to sync changes against university's records. We provide a registration panel where students can choose their name, but it is the only way to indicate an arbitrary name. Once students are registered, they will not able to change their profile details. At the moment, the only way is asking your administrator to perform the changes accordingly.

We will consider your suggestion and, if you are willing to contribute to this project, we are open to discuss and review Pull Requests for new features!
