### ISSUE TITLE
Unable to login due to e-mails case sensitivity

### ISSUE THREAD

**Issue by fntneves** [Hackathonners/swap#7]
### Expected Behavior
Users should be able to login with their e-mails even when case mismatch the original one.

### Current Behavior
Considering that the User A is registered with the e-mail "a@a.com".
When User A tries to login with "A@a.com", an invalid authentication error is returned.

### Possible Solution
Convert e-mails to a consistent case for further comparison.

### Steps to Reproduce (for bugs)
1. Register a new user with e-mail 'a@a.com'
2. Login with 'A@a.com'
3. See the **Invalid credentials** flash message

### Context
Users are unable to login with e-mails they used to register in Swap.

### Your Environment
Chrome 61.0.3163.100
MacOS 10.12.6

**Comment by Hugainz** [comment]
@fntneves I'd like to work on this.
